### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by alimaqsood3** [amirsanni/Video-Call-App-NodeJS#1]
Hello, sir 
i am a student and want to test your app online.But when i tried to upload on heroku is gives error of logs.like npm start than npm crash

**Comment by amirsanni** [comment]
Can you share the exact error message? It's most likely a configuration issue.

**Comment by alimaqsood3** [comment]
thank you soo much sir.the issue is solved

**Comment by Miltonbhowmick** [comment]
@amirsanni , How did you solved it? Please share your solution.
**Application logs** is showing on my one!
