### ISSUE TITLE
Not working on different network

### ISSUE THREAD

**Issue by Renjithcse** [amirsanni/Video-Call-App-NodeJS#10]
Not working with different network.With in same network working fine. I tested on our side and also your demo.

**Comment by amirsanni** [comment]
Unfortunately, I cannot recreate this. Which browsers are you using? Also, is there any error in the browser console?

**Comment by Till0196** [comment]
Is it possible to support https for the local network?

**Comment by amirsanni** [comment]
Yes but you'll have to set that up yourself.

**Comment by Till0196** [comment]
I wrote the code to support https easily.  But it doesn't work.  Please help me.
```
var express = require('express');
var app = express();
var fs = require('fs');

var options = { 
key: fs.readFileSync('./private.pem'),
cert: fs.readFileSync('./cert.pem') };  

var server = require('https').createServer(options, app);
var io = require('socket.io')(server);
var stream = require('./ws/stream');
var path = require('path');
var favicon = require('serve-favicon');

app.use(favicon(path.join(__dirname, 'favicon.ico')));
app.use('/assets', express.static(path.join(__dirname, 'assets')));

app.get('/', (req, res)=>{
    res.sendFile(__dirname+'/index.html');
});


io.of('/stream').on('connection', stream);

server.listen(3000);
```

**Comment by nikhillad01** [comment]
Not working with different network.

**Comment by nikhillad01** [comment]
> Not working with different network.With in same network working fine. I tested on our side and also your demo.

found any solutions on this ?

**Comment by amirsanni** [comment]
The different network issue is most likely due to the turn/stun server used. It's a free one provided by xirsys and has a monthly limit, which is usually exhausted because many people use it on the demo. I'll advise you get a free one yourself or use any other one.

**Comment by Renjithcse** [comment]
> > Not working with different network.With in same network working fine. I tested on our side and also your demo.
> 
> found any solutions on this ?

Its due to turn/stun server. U can get free one from xirsys or implement your own turn.stun server

**Comment by amirsanni** [comment]
I just found out my xirsys account was disabled by Xirsys, hence the issue. If you encounter this issue, please get a TURN/STUN server of your choice and use.
