### ISSUE TITLE
Run via localhost

### ISSUE THREAD

**Issue by huelgasjcowork** [amirsanni/Video-Call-App-NodeJS#12]
Hi good day, your project was awesome.

I tried your demo online, it was running smoothly. But, I intended to run in localhost. In my own machine is working fine, but when I network in a different machine (Windows 10, Updated Google chrome) it won't work as I assumed.

In the different machine, the error says that
"User media, not available". 
backtrace: 
at Object.getUserFullmedia(helper.js:65)
at getAndSetUserStream (rtc.js:108)
at rtc.js:37

**Comment by amirsanni** [comment]
Hi

I want to believe you're doing this with an IP. Browsers won't give access
to user media except you're on localhost or you have SSL on your domain.

Amir Sanni
