### ISSUE TITLE
Deployment 

### ISSUE THREAD

**Issue by Lavanya321320** [amirsanni/Video-Call-App-NodeJS#13]
Hi
Your code is working very well, i tried to deploy in vercel now. Sh but am getting npm issue. Can you please tell about deployment. How to deploy and test the code in live

**Comment by amirsanni** [comment]
Not sure what issue you have with npm but deploying is quite straightforward.

- Clone the repo
- Change the port the app is listening on (optional)
- run `npm install`. Of course, you must have `node` and `npm` installed on your server.
- Ensure your domain has SSL.
- Access the app with a browser.

What's the exact issue you have with `npm`?

**Comment by Lavanya321320** [comment]
Failed to load resource: the server responded with a status of 404 () socket.io.js
In localhost working correctly but when move the code to now.sh site to test using github am getting above error

**Comment by Lavanya321320** [comment]
It is possible to use more than one camera on the code for example option to choose  front and back camera or webcame .

**Comment by amirsanni** [comment]
You can easily add this functionality by getting the available devices and
giving the user the option to select their preference.

Amir Sanni
