### ISSUE TITLE
Cross Browser is not working 

### ISSUE THREAD

**Issue by praveshbansal** [amirsanni/Video-Call-App-NodeJS#15]
Hi Amir, 

I tried your code it seems cross-browser is not working with this code.

Firefox screenshot 
![image](https://user-images.githubusercontent.com/10232127/83358363-db571680-a36a-11ea-96a9-f58617950d9d.png)

Chrome Screenshot 
![image](https://user-images.githubusercontent.com/10232127/83358378-f7f34e80-a36a-11ea-953f-1486e7e59557.png)

Case 1 ) Both the user is joining through Chrome or Firefox is working 
Case 2 ) Cross-Browser Application is not working 

Could you guide me with this ?

Regards, 
Pravesh Bansal

**Comment by amirsanni** [comment]
Hi,

Judging by the error message, the application could not access one of the users’ media devices. This could be as a result of a couple of things:

1. The user did not grant access when the app requested for it.
2. Another app/browser/tab is using the media devices, thus preventing the app to access it.

Ensure no other app/browser is using the media devices and try again.

In addition, like I mentioned in the README, the TURN/STUN server used for the demo is no longer active, so it is not reliable. I am working on setting up my own to make it more reliable. You can look for alternatives to mitigate this issue.

Regards,

**Comment by praveshbansal** [comment]
Hi Amir, 

Thanks for reaching out quickly. 

To answer your query 
1) The user has given the permission I have tried it locally already and the User has provided the permission as well. 
Screenshot for Firefox 
![image](https://user-images.githubusercontent.com/10232127/83398571-7e557200-a3f7-11ea-9537-b95f5bcaa829.png)

2) I have created a fresh TURN/STUN server as you mentioned in your README.

Firefox Screenshot after giving permission to access.
![image](https://user-images.githubusercontent.com/10232127/83398659-b066d400-a3f7-11ea-9cf4-bad360436068.png)

Regards, 
Pravesh

**Comment by amirsanni** [comment]
Not sure why that error occurs even after giving permission. Just a trial, can you use the inbuilt microphone instead of the Headset?

**Comment by praveshbansal** [comment]
yes I just tried that as well it did not work .. Let me deploy the service on some server and then test it.

**Comment by amirsanni** [comment]
Alright

Amir Sanni

**Comment by praveshbansal** [comment]
Hey Amir, 

It seems it is working when I deployed it on the server. 

This issue is only local not when you access from different machines. :)

Thanks again :)

Regards, 
Pravesh

**Comment by amirsanni** [comment]
Good. Glad to hear that. Now I just thought of it. If you were using IP address other than 127.0.0.1 on localhost, most modern browsers won't give access to media devices. That might have played a role.

**Comment by praveshbansal** [comment]
Nope I was using 127.0.0.1 

Something like this which is handling the modern browser 
 if (details.family === 'IPv4' && details.address !== '127.0.0.1') {
          console.log(details.address)
          socket.emit('ipaddr', details.address);
        }

But My understanding of the issue is as chrome already had the access to mediaDevices and when Firefox also tried to access the same mediaDevices it got busy error or null . Hence causing this issue. 

Regards, 
Pravesh

**Comment by amirsanni** [comment]
Alright. Guess that explains it.

Thanks
