### ISSUE TITLE
How many participant can be added in one room ?

### ISSUE THREAD

**Issue by praveshbansal** [amirsanni/Video-Call-App-NodeJS#16]
I believe as this is a peer to peer communication there will be a limitation with the bandwidth and hence a number of participants allowed to be in a room?

If you have done the testing are you aware of how many can be allowed to be added in the room?
If I want to add such a limit that can be done on the server code. Correct me if I am wrong?

Regards, 
Pravesh Bansal

**Comment by amirsanni** [comment]
True. The maximum I have done without any real issue is 4 devices. This also depends on the capabilities of the devices used.

You can limit the number of users in a room. This limit can be done in `ws/stream.js`. by checking for the number of users in a room before allowing new users to join.

**Comment by praveshbansal** [comment]
Thanks, Amir. 
This makes sense. I will limit the number of users than to 4 which majorly handle all the use case.
