### ISSUE TITLE
socket.io Method Not Allowed 405

### ISSUE THREAD

**Issue by aloveric** [amirsanni/Video-Call-App-NodeJS#17]
Hi,

I followed all your points, but still not working on my sever: https://api.woo-interactive.com/

- Clone the repo
- run npm install.
- Ensure domain has SSL
- New Ice server account

<img width="1418" alt="Screen Shot 2020-06-04 at 1 26 15 AM" src="https://user-images.githubusercontent.com/8198881/83668431-87665f00-a602-11ea-987b-04995187112e.png">

**Comment by amirsanni** [comment]
I need to understand your server setup. Is the app served by Nodejs or Apache or Nginx?

For the web socket connection on a public IP, you have two options:

1. Configure your nodejs to listen on SSL and update the web socket connection to reference the full web socket URL.
2. Use your Apache/nginx/etc server as a proxy to the node server.

**Comment by aloveric** [comment]
It is a Win2012R2 with IIS8.5.
Let me try to config a web socket URL.
Thanks for your feedback.

**Comment by amirsanni** [comment]
Alright. Will be waiting for your feedback.

Amir Sanni

**Comment by amirsanni** [comment]
@aloveric Were you able to get it to work?

**Comment by aloveric** [comment]
@amirsanni Apologize for late response, a little busy with my new [hardware project](https://github.com/woointeractive/PersonalWeatherStation) :)  
Will check this issue soon.

**Comment by amirsanni** [comment]
Alright
