### ISSUE TITLE
403 Forbidden: Socket.io

### ISSUE THREAD

**Issue by huelgasjcowork** [amirsanni/Video-Call-App-NodeJS#18]
![Screen Shot 2020-06-05 at 3 47 41 AM](https://user-images.githubusercontent.com/34116186/83803683-95d67880-a6df-11ea-8868-b5fe3a24abd9.png)

Hello,

I followed all your instructions, but still not working on my server: https://letstalk.jmahuelgas.com/

1. Clone the repo
2. run npm install.
3. Ensure domain has SSL
4. New Ice server account

Note: I edited my document root folder permission into 777 and running on Apache.

**Comment by amirsanni** [comment]
This is an issue with the server setup. Please confirm if you're able to run it successfully in localhost.

I also need to understand your server setup for me to be able to give any advice on what the issue is.

**Comment by huelgasjcowork** [comment]
Thank you for your quick response!

It was successfully running on http://localhost:3000/. 

I have a server hosting run on Linux and Apache.
I access through an ssh terminal: $ user@webmaster.com

It's already installed NPM 6.9.0, node 10.16.3, and PHP 7.3.13. 
For additional setup:
1. I have a subdomain and set an absolute path for the app. e.g.:
 /domains/jmahuelgas.com/public_html/letstalk/src/
2. I downloaded socket.io and put it inside on the project.

Can you please give me advice on how to setup server hosting and run this application on live-site?

**Comment by amirsanni** [comment]
You can run it the same way you did on localhost. You can install `pm2` to manage the app process.

**Comment by huelgasjcowork** [comment]
Okay got it, but I figured out and run smoothly. I forgot to open port 3000 TCP incoming/outcoming which was a firewall in server blocked it.

**Comment by amirsanni** [comment]
Alright, cool.
