### ISSUE TITLE
How to implement in Android Native

### ISSUE THREAD

**Issue by sureapps** [amirsanni/Video-Call-App-NodeJS#20]
I am Android Developer and i need the video call application.So, can you help me ?
I have setup on my server and working fine.

But how can i manage to android mobile can you help me which api and how to join room using android Application or How to join any port or socket the i will join the video conference in android mobile.

Thank amirsanni

**Comment by amirsanni** [comment]
Hi,

There is an Android version of socket.io <http://socket.io/> that you can use for connecting to web socket.

I am not an Android developer, so I may not be able to help much here but there is a webrtc implementation in Java that you can use as well.

1. https://socket.io/blog/native-socket-io-and-android/ <https://socket.io/blog/native-socket-io-and-android/>
2. https://webrtc.github.io/webrtc-org/native-code/android/ <https://webrtc.github.io/webrtc-org/native-code/android/>
