### ISSUE TITLE
have to work on local network

### ISSUE THREAD

**Issue by vino6665** [amirsanni/Video-Call-App-NodeJS#21]
hello sir,

wonder full code , which i m looking for.. this is code working fine in localhost...

how could i change it to work between LAN

please help...

**Comment by amirsanni** [comment]
Nothing prevents it from working on LAN aside the fact that browsers won't grant access to media devices on an address/domain other than localhost/127.0.0.1. If you can take care of that, then no problem.

**Comment by vino6665** [comment]
thanks for your quick response,,,if it so, how this application will be implemented,( if i could not access via ip other that localhost, How the conference will happen from different location/ pc )

**Comment by amirsanni** [comment]
You will need to host it on a server with a public IP and ensure it is served via SSL.

**Comment by vino6665** [comment]
thanks ... is it possible with apache....or any other open source available ...could you guide me regarding to host this app

**Comment by vino6665** [comment]
thanks ... is it possible with apache....or any other open source available ...could you guide me regarding to host this app..

only for local area network.... not for internet ...

**Comment by amirsanni** [comment]
It's possible with Apache, and on a LAN. I'm not sure I can help with that.
You can as well just use node to run the app.

You'll need to setup a self signed certificate on the hosting device/server
that will be trusted by all the connecting devices.

However, I'm not sure how I can help.

Amir Sanni
