### ISSUE TITLE
working on domain

### ISSUE THREAD

**Issue by sohailes** [amirsanni/Video-Call-App-NodeJS#23]
hi, 
code working locally very fine, but when i hosted it to live server its not working video streaming of users are showing them. 

like my video not showing to user2, and user2's video not showing me. 
can you help me out.

thank you.

**Comment by amirsanni** [comment]
You probably need a TURN/STUN server. Did it work with two users on the same network?

**Comment by sohailes** [comment]
yes it works on same networks, 

only problem create when users are on different networks

**Comment by amirsanni** [comment]
You need to set up your TURN/STUN server or use a free one. [Xirsys](https://xirsys.com/) offers free but limited access to theirs. You can check it out.

Once you have the details, you can replace it in `helpers.js` file, `getIceServer()`.

**Comment by sohailes** [comment]
and one more question, is it possible that a user can see other's stream but not streaming its own?

**Comment by sohailes** [comment]
> You need to set up your TURN/STUN server or use a free one. [Xirsys](https://xirsys.com/) offers free but limited access to theirs. You can check it out.
> 
> Once you have the details, you can replace it in `helpers.js` file, `getIceServer()`.

ok thanks, i will check that. and if i feel any issue i will contact you.

**Comment by amirsanni** [comment]
No problem

**Comment by sohailes** [comment]
> and one more question, is it possible that a user can see other's stream but not streaming its own?

any idea about this ?

**Comment by amirsanni** [comment]
> and one more question, is it possible that a user can see other's stream but not streaming its own?

Yes. Clicking on the video icon on the top-right will toggle his stream (on/off).

**Comment by sohailes** [comment]
okay. thanks.

**Comment by sohailes** [comment]
> You need to set up your TURN/STUN server or use a free one. [Xirsys](https://xirsys.com/) offers free but limited access to theirs. You can check it out.
> 
> Once you have the details, you can replace it in `helpers.js` file, `getIceServer()`.

Hi, i created account at Xirsys, but i can't find the username ,credentials and urls that you defined in getIceServer. how can i get these?

**Comment by amirsanni** [comment]
Unfortunately, I can no longer access my Xirsys account but it's usually to the right, on your dashboard.

**Comment by sohailes** [comment]
> > and one more question, is it possible that a user can see other's stream but not streaming its own?
> 
> Yes. Clicking on the video icon on the top-right will toggle his stream (on/off).

sir i have a case, let me explain 
there are three users user1, user2, user3
user1 and user2 are on video chat,  but i want user3 can only wacth other 2 users streaming by not posting his own streamig.

**Comment by amirsanni** [comment]
Oh! That is beyond the scope of this demo. Only way you can achieve that
with this is for user 3 to toggle off his camera.

Amir Sanni
