### ISSUE TITLE
Pleaase help in hybrid video conference app

### ISSUE THREAD

**Issue by atulrawat85** [amirsanni/Video-Call-App-NodeJS#25]
Hello Amir, i followed your code from a long time, its so nice that u update projects time to time.

Amir i want to create a html5 css mobile hybrid app client of your nodejs conference app please guide.
Please explain what things are need to be port in mobile app and how to access socket server from remotely thru mobile device..
it may involve cors, how to bind cors to mobile app only..

please guide..

**Comment by amirsanni** [comment]
Hi @atulrawat85, sorry for the late response. The index.html file and the client-side js scripts are the main things you need. You just have to update the URL to the client-side socket.io and the other js dependencies.
