### ISSUE TITLE
deployment and users connection

### ISSUE THREAD

**Issue by alimaqsood3** [amirsanni/Video-Call-App-NodeJS#3]
hello sir
my question is how i can deploy this on ubantu server 
and how much users can connect at a time

**Comment by amirsanni** [comment]
Clone the repo, then do `npm install`. Only other you need is to determine which port you want the app to run on, based on your preference.

As for the number of users, I don't know the limit. The limit is into millions if you have the resources.

**Comment by alimaqsood3** [comment]
thanks sir for the rply 
one more thing how much people can conect at on time

**Comment by amirsanni** [comment]
Like I said, it all depends on what your infrastructure can handle.
