### ISSUE TITLE
same person is displayed multiple times

### ISSUE THREAD

**Issue by Nemra1** [amirsanni/Video-Call-App-NodeJS#30]
I don't know what is the problem but when the room has more than 3 visitors.. 
same person is displayed multiple times even in demo url...

**Comment by amirsanni** [comment]
Hi, I have not experienced this but this may be as a result of a limitation on the device used. The app is suited for between 3-4 users, depending on the capability of the devices.

**Comment by Nemra1** [comment]
nothing help
