### ISSUE TITLE
stream error: NotFoundError: Requested device not found

### ISSUE THREAD

**Issue by equintanillam** [amirsanni/Video-Call-App-NodeJS#34]
Hello, thank for your application,
but have one error in localhost and demo.

What can be the error?
![image](https://user-images.githubusercontent.com/20546822/92553438-4e5d0c80-f239-11ea-8a06-63e245942d2c.png)

**Comment by amirsanni** [comment]
One or both the camera and microphone are not accessible.

From MDN:

NotFoundErrorNo media tracks of the type specified were found that satisfy
the given constraints.
Amir Sanni

**Comment by equintanillam** [comment]
Thanks, I see that you also changed the server stun and turn
It is correct to see and use your connection data

return {
            iceServers: [
                {
                    urls: ["stun:stun.speakez.chat"]
                },
                {
                    username: "sez",
                    credential: "Qbb8ccQxBrV5VL8R",
                    urls: [
                        "turn:turn.speakez.chat:3478?transport=udp",
                        "turn:turn.speakez.chat:3478?transport=tcp"
                    ]
                }
            ]
        };
