### ISSUE TITLE
index.js:83 WebSocket connection to 'wss://chat.1410inc.xyz/socket.io/?EIO=3&transport=websocket&sid=de9bOZkoj4ZpmDsqACUg' failed: 

### ISSUE THREAD

**Issue by soundinworship** [amirsanni/Video-Call-App-NodeJS#45]
Hi, 

Thank you so much for building this!

I'm only having one issue. On my server I get the same console error as the below:
![image](https://user-images.githubusercontent.com/76238093/115972668-c7d21280-a51d-11eb-993c-03e93f502ad5.png)

Any idea to work around this?

Thanks!

**Comment by amirsanni** [comment]
Are you testing on your local computer or on the demo site?
