### ISSUE TITLE
Avoid using innerHTML

### ISSUE THREAD

**Issue by shreyshreyansh** [amirsanni/Video-Call-App-NodeJS#56]
Anyone can mess with your website just by giving html commands

![Screenshot 2021-08-15 115741](https://user-images.githubusercontent.com/53744971/129469429-4ce7390c-7939-4104-b50b-7d30b44519e3.png)

**Comment by amirsanni** [comment]
The HTML in the chat is filtered using XSS filter, so no issue here.

<img width="984" alt="helpers js — video-call-app-nodejs 2021-09-25 10 PM-12-36" src="https://user-images.githubusercontent.com/6107185/134786054-3b017bbf-e25a-4f49-9a3c-92e39582629e.png">
