### ISSUE TITLE
Heroku deployed but the app not working on different networks

### ISSUE THREAD

**Issue by Miltonbhowmick** [amirsanni/Video-Call-App-NodeJS#61]
The app does not working whenever 2 person connected from different networks. I tried this after deploying to heroku.
What is the reason of this issue?

Here is the deployed link,
https://video-chat-002.herokuapp.com/

**Comment by sciapuscio** [comment]
You have to set up STUN and TURN TLS servers. You can create your own Coturn server if you have a static public IP, or use a third-party service like https://dashboard.metered.ca/turnserver.
