### ISSUE TITLE
Code is not complete

### ISSUE THREAD

**Issue by leosofttech** [amirsanni/Video-Call-App-NodeJS#8]
The app is not working. I think the code is not same as demo.

**Comment by amirsanni** [comment]
It is. The demo is pulled from this repository.

What error are you getting?

Amir Sanni

**Comment by leosofttech** [comment]
I run the code. The video is not loaded even after npm install...

How to run this code correctly??

**Comment by leosofttech** [comment]
http://video-call-03.000webhostapp.com/?room=h_9s15uu62kx5


Its the site i hosted

**Comment by amirsanni** [comment]
Did you run the app at all? `node src/app.js`
